# Generated by Django 5.0.4 on 2024-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование организации')),
                ('text', models.CharField(max_length=250, verbose_name='Основной текст')),
                ('preimushestva', models.CharField(max_length=250, verbose_name='Преимущества')),
                ('img', models.FileField(upload_to='catalog/img/')),
            ],
        ),
    ]
