# Generated by Django 5.0.4 on 2024-05-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_first_page_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems', models.TextField(verbose_name='Проблемы')),
            ],
        ),
        migrations.AlterField(
            model_name='first_page',
            name='img',
            field=models.ImageField(default='img', upload_to='catalog/img/'),
        ),
    ]
