# Generated by Django 5.0.4 on 2024-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_second_page_alter_first_page_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourth_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заглавная строка')),
                ('list_title', models.CharField(max_length=250, verbose_name='Первая строка в списке')),
                ('list_text', models.TextField(verbose_name='Основной текст списка')),
            ],
        ),
    ]
