# Generated by Django 5.0.4 on 2024-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fourth_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eighth_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p8title', models.CharField(max_length=250)),
                ('p8image', models.ImageField(upload_to='')),
                ('p8content', models.TextField()),
                ('p8footer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='fourth_page',
            name='list_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fourth_page',
            name='list_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fourth_page',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
