# Generated by Django 5.0.4 on 2024-06-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_fourth_page_img8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourth_page',
            name='img8',
        ),
    ]
