# Generated by Django 5.0.4 on 2024-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_fourth_page_img8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighth_page',
            name='p8image',
            field=models.ImageField(upload_to=''),
        ),
    ]
