# Generated by Django 5.0.4 on 2024-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_eighth_page_p8image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eighth_page',
            name='p8image',
            field=models.ImageField(default='img', upload_to='catalog/img/'),
        ),
    ]
