# Generated by Django 5.0.4 on 2024-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ten_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nine_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p9_title', models.CharField(max_length=250)),
                ('p9_1', models.ImageField(default='img', upload_to='catalog/img/')),
                ('p9_2', models.ImageField(default='img', upload_to='catalog/img/')),
                ('p9_3', models.ImageField(default='img', upload_to='catalog/img/')),
                ('p9_4', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_5', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_6', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_7', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_8', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_9', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_10', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_11', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_12', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_13', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_14', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
                ('p9_15', models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/')),
            ],
        ),
    ]
