# Generated by Django 5.0.4 on 2024-06-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_nine_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='img', upload_to='catalog/img/')),
                ('obect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.nine_page')),
            ],
        ),
    ]
