# Generated by Django 5.0.4 on 2024-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nine_page',
            name='p9_1',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/'),
        ),
        migrations.AlterField(
            model_name='nine_page',
            name='p9_2',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/'),
        ),
        migrations.AlterField(
            model_name='nine_page',
            name='p9_3',
            field=models.ImageField(blank=True, default='img', null=True, upload_to='catalog/img/'),
        ),
    ]
